version: '2'

services:
  db:
    image: postgres
  web:
    build: 
        context: ./django
        dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
        - ./django:/code
    depends_on:
      - db
