# Copyright (C) 2018 FU Berlin and HAW Hamburg
#
# This file is subject to the terms and conditions of the GNU Lesser
# General Public License v2.1. See the file LICENSE in the top level
# directory for more details.

version: '2'

services:
  db:
    image: postgres
  web:
    build: 
        context: ./django
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - ./django:/code
    depends_on:
      - db
  builder:
    build:
        context: ./builder
        dockerfile: Dockerfile
    command: bash -c "chmod +x /code/docker-entry.sh && /code/docker-entry.sh"
    volumes:
      - ./builder:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
