version: '2'

services:
  db:
    image: postgres
  web:
    build: 
        context: ./django
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - ./django:/code
    depends_on:
      - db
  builder:
    build:
        context: ./builder
        dockerfile: Dockerfile
    command: bash -c "chmod +x /code/docker-entry.sh && /code/docker-entry.sh"
    volumes:
      - ./builder:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
