# Copyright (C) 2018 FU Berlin and HAW Hamburg
#
# This file is subject to the terms and conditions of the GNU Lesser
# General Public License v2.1. See the file LICENSE in the top level
# directory for more details.

version: '2'

services:
  db:
    image: postgres
  web:
    build: 
        context: ./django
        dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
        - ./django:/code
    depends_on:
      - db
